services:
  - type: web
    name: my-react-app
    env: static
    staticPublishPath: build
    buildCommand: npm install && npm run build
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18
